export const StatusProcess = {
    INICIADA: "INICIADA",
    AGUARDANDO_VISITA: "AGUARDANDO_VISITA",
    AGUARDANDO_APROVACAO: "AGUARDANDO_APROVACAO",
    APROVADA: "APROVADA",
    CANCELADA: "CANCELADA",
    REPROVADA: "REPROVADA"
}